### ISSUE TITLE
need to setup rss feed

### ISSUE THREAD

**Issue by Grippentech** [UNIS-Radio/UNIS-Radio.github.io#4]

**Comment by TimCargan** [comment]
why

**Comment by Grippentech** [comment]
Sweeney needs it to be able to use iTunes podcasts.

**Comment by TimCargan** [comment]
##did you do it yet

**Comment by 16msweeney** [comment]
Im not messing with iTunes.  Soundcloud embeds well on Facebook.  
____
Michael Joseph Sweeney T4
United Nations International School
16msweeney@unis.org <mailto:16msweeney@unis.org>

**Comment by TimCargan** [comment]
But we are finally getting fb traction
